services:

  service_a:
    build:
      context: ./service_a
      dockerfile: Dockerfile
    ports:
      - 8181:8181
    environment:
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - OTEL_SERVICE_NAME=service_a
    depends_on:
      - zipkin
      - service_b

  service_b:
    build:
      context: ./service_b
      dockerfile: Dockerfile
    ports:
      - 8282:8282
    environment:
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - OTEL_SERVICE_NAME=service_b
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411