
receivers:
  otlp:
    protocols:
      grpc:
        # endpoint: 0.0.0.0:4317
        
processors:
  batch:

exporters:
  zipkin:
    endpoint: "http://zipkin-service:9411/api/v2/spans"
    format: proto

  # prometheus:
  #   endpoint: "0.0.0.0:8889"
 
  logging:  
    
  # otlp:
  #   endpoint: jaeger-service:4317
  #   tls:
  #     insecure: true
          
service:
  pipelines:
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin, logging]
    
  
